stages:
  - build
  - package
  - deploy-dev
  - deploy-prd

variables:
  SERVICE_NAME: iadp-mobile-front-web

build:
  image: $REGISTRY_ADDRESS/devops/nodejs/build
  stage: build
  only:
    - tags
    - develop
    - testing
    - release
  script:
    - yarn config get registry && yarn && yarn run lint && yarn run build
  artifacts:
    paths:
      - dist
      - Dockerfile
    expire_in: 2 hrs
  tags:
    - nodejs

package:
  image: $REGISTRY_ADDRESS/devops/docker/package
  stage: package
  variables:
    GIT_STRATEGY: none
  only:
    - tags
    - develop
    - testing
    - release
  script:
    - package
  tags:
    - docker

.deploy_job: &deploy_job
  image: $CI_REGISTRY/devops/docker/deploy
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script: deploy -service $SERVICE_NAME -template web -vars host=e.jydata.com,port=80
  tags:
    - nodejs
  only:
    - /^release\/.*$/

deploy-dev:
  <<: *deploy_job
  stage: deploy-dev
  variables:
    GIT_STRATEGY: none
  dependencies: []
  environment: aiads-dev
  tags:
    - docker


deploy-prd:
  <<: *deploy_job
  stage: deploy-prd
  variables:
    GIT_STRATEGY: none
  dependencies: []
  environment: aiads-prd
  retry: 3
  tags:
    - docker
  when: manual
