stages:
  - build
  - package
  - deploy-dev
  - deploy-qas
  - deploy-prd

variables:
  SERVICE_NAME: iadp-mobile-front-web


build:
  image: $REGISTRY_ADDRESS/devops/nodejs/build
  stage: build
  only:
    - /^release\/.*$/
    - tags
    - develop
    - testing
  script:
    - yarn config get registry && yarn && yarn run lint && yarn run build
  artifacts:
    paths:
      - dist
      - Dockerfile
    expire_in: 2 hrs
  tags:
    - nodejs

package:
  image: $REGISTRY_ADDRESS/devops/docker/package
  stage: package
  variables:
    GIT_STRATEGY: none
  only:
    - /^release\/.*$/
    - tags
    - develop
    - testing
  script:
    - package
  tags:
    - docker

.deploy_job: &deploy_job
  image: $REGISTRY_ADDRESS/devops/docker/deploy
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script: deploy -service $SERVICE_NAME -template web -vars host=e.aiads-dev.com,port=80
  tags:
    - docker

deploy-dev:
  <<: *deploy_job
  only:
    - /^release\/.*$/
  stage: deploy-dev
  environment: aiads-dev

deploy-qas:
  <<: *deploy_job
  only:
    - /^release\/.*$/
  stage: deploy-dev
  environment: aiads-qas


deploy-prd:
  <<: *deploy_job
  only:
    - /^release\/.*$/
  stage: deploy-prd
  environment: aiads-prd
  retry: 2
  when: manual
